---
APPLY_FIXES: all
PARALLEL: true
VALIDATE_ALL_CODEBASE: true
GITHUB_STATUS_REPORTER: true
SARIF_REPORTER: true
IGNORE_GENERATED_FILES: true
PRINT_ALPACA: false
SHOW_SKIPPED_LINTERS: false
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false

ENABLE_LINTERS:
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - JSON_PRETTIER
  - PHP_PHPCS
  - PHP_PHPSTAN

DISABLE_LINTERS:
  - REPOSITORY_DEVSKIM

PHP_PHPCS_CLI_LINT_MODE: project
PHP_PHPCS_ARGUMENTS: "--warning-severity=0"

PHP_PHPSTAN_CLI_LINT_MODE: project
PHP_PHPSTAN_CONFIG_FILE: phpstan.neon

FILTER_REGEX_EXCLUDE: "(vendor/|node_modules/|\\.github/|\\.git/|composer\\.lock|package-lock\\.json)"
