---
name: PR Lint

on:
  pull_request:
    branches: [master, main]

jobs:
  lint:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ivuorinen/actions/pr-lint@459781a253d1c53960506b124ae3beaa1090e2a3 # v2026.03.22
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
