---
name: PR Lint

on:
  pull_request:
    branches: [master, main]

jobs:
  lint:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ivuorinen/actions/pr-lint@dc85cef1c285edd3d2edcb4a7c82bdd08ccc7c56 # v2026.03.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
