---
name: PR Lint

on:
  pull_request:
    branches: [master, main]

jobs:
  lint:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ivuorinen/actions/pr-lint@7f6a23b59316795c4b3cb3b3b28dd53e53655a33 # v2026.03.11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
