---
name: Release Monthly

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ivuorinen/actions/release-monthly@0795e029fb0083fe692fb10b4ed6132822b069e6 # v2026.04.06
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
