---
name: Release Monthly

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ivuorinen/actions/release-monthly@d1af04260d903f572ee953cc790ff7c1410709a6 # v2026.03.05
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
