---
name: Release Monthly

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ivuorinen/actions/release-monthly@f2d15a840e8888ba4f0c348ea70b6522cf2dc541 # v2026.04.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
