---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: ivuorinen/actions/stale@4b58f07a1440225619a22978b03bda64c6889886 # v2026.07.03
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
