---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: ivuorinen/actions/stale@dc85cef1c285edd3d2edcb4a7c82bdd08ccc7c56 # v2026.03.20
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
