---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  schedule:
    - cron: "34 5 * * *"
  workflow_call:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  SyncLabels:
    uses: ivuorinen/.github/.github/workflows/sync-labels.yml@main
